version: "3"
services:

  # Core API services are pinned, HA is provided for functions.
  gateway:
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8080:8080
    image: functions/gateway:0.6.7-armhf
    networks:
      - functions
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

#    prometheus:
#      image: alexellis2/prometheus-armhf:1.5.2
#      volumes:
#        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#        - ./prometheus/alert.rules:/etc/prometheus/alert.rules
#      command: "-config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.memory-chunks=10000 --alertmanager.url=http://alertmanager:9093"
#      ports:
#        - 9090:9090
#      depends_on:
#        - gateway
#        - alertmanager
#      environment:
#        no_proxy: "gateway"
#      networks:
#        - functions
#      deploy:
#        placement:
#          constraints: [node.role == manager]
#
#    alertmanager:
#      image: alexellis2/alertmanager-armhf:0.5.1
#      environment:
#        no_proxy: "gateway"
#      volumes:
#        - ./prometheus/alertmanager.yml:/alertmanager.yml
#      command:
#        - '-config.file=/alertmanager.yml'
#      networks:
#        - functions
#      ports:
#        - 9093:9093
#      deploy:
#        placement:
#          constraints: [node.role == manager]

  # Functions go here

networks:
  functions:
    driver: overlay
