version: "3.4"
services:

  # Core API services are pinned, HA is provided for functions.
  gwnginx:
    image: riggerthegeek/faas-password-gateway:latest
    ports:
      - 8080:8080
    depends_on:
      - gateway
    networks:
      - functions
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == manager]
    secrets:
      - openfaas_htpasswd

  gateway:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    image: functions/gateway:0.6.9-armhf
    networks:
      - functions
    environment:
      read_timeout: 10    # set both here, and on your functions
      write_timeout: 10   # set both here, and on your functions
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == manager]

#  prometheus:
#    image: alexellis2/prometheus-armhf:1.5.2
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
#    command: "-config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.memory-chunks=10000 --alertmanager.url=http://alertmanager:9093"
#    ports:
#      - 9090:9090
#    depends_on:
#      - gateway
#      - alertmanager
#    environment:
#      no_proxy: "gateway"
#    networks:
#      - functions
#    configs:
#      - source: prometheus-alerts
#        target: /etc/prometheus/alert.rules
#      - source: prometheus
#        target: /etc/prometheus/prometheus.yml
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#        delay: 10s
#        max_attempts: 3
#        window: 120s
#      update_config:
#        parallelism: 1
#        delay: 10s
#      placement:
#        constraints: [node.role == manager]

#  alertmanager:
#    image: alexellis2/alertmanager-armhf:0.5.1
#    environment:
#      no_proxy: "gateway"
#    volumes:
#      - ./prometheus/alertmanager.yml:/alertmanager.yml
#    command:
#      - '-config.file=/alertmanager.yml'
#    networks:
#      - functions
#    ports:
#      - 9093:9093
#    configs:
#      - source: prometheus-alertmanager
#        target: /alertmanager.yml
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#        delay: 10s
#        max_attempts: 3
#        window: 120s
#      update_config:
#        parallelism: 1
#        delay: 10s
#      placement:
#        constraints: [node.role == manager]

  # Functions go here
  distance-finder:
    image: riggerthegeek/function-distance-finder:latest
    labels:
      function: "true"
    depends_on:
      - gateway
    networks:
      - functions
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s

configs:
  prometheus-alerts:
    file: ./prometheus/alert.rules
  prometheus-alertmanager:
    file: ./prometheus/alertmanager.yml
  prometheus:
    file: ./prometheus/prometheus.yml

networks:
  functions:
    driver: overlay

secrets:
  openfaas_htpasswd:
    external: true
